# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Webia Website
    url: https://webia.io
  - name: api
    url: https://api.webia.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.webia.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://webia.io/assets/logo.png
  name: Webia
  introTitle: "**webia** is a public service for websites general data."
  introMessage: webia status page service with upptime
  navbar:
    - title: Webia
      href: https://webia.io
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
